DROP SEQUENCE B_SEQ;
SELECT * FROM B;
DROP TABLE B;
CREATE TABLE B(
    BNO NUMBER(8) PRIMARY KEY,
    BTITLE VARCHAR2(100) NOT NULL,
    BCONTENT CLOB,
    BFILE VARCHAR2(4000)
);
CREATE SEQUENCE B_SEQ MAXVALUE 99999999 NOCYCLE NOCACHE;
INSERT INTO B VALUES (B_SEQ.NEXTVAL, '제목1','내용','nothing.jpg');
INSERT INTO B VALUES (B_SEQ.NEXTVAL, '제목2','내용',NULL);
commit;
-- search조건 없을 때
SELECT * FROM B ORDER BY BNO DESC;
SELECT * FROM (SELECT ROWNUM RN, A.* FROM (SELECT * FROM B ORDER BY BNO DESC) A)
    WHERE RN BETWEEN 2 AND 2;
-- search조건이 btitle일 때
SELECT * FROM B where btitle like '%'||'제'||'%'  ORDER BY BNO DESC;
